name: Deploy to Server

on:
  push:
    branches:
      - main # или другая ветка, в которую ты пушишь

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js and build assets
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
          npm install
          npm run build

      - name: Migrate tables
        run: |
          php artisan optimize
          php artisan migrate --force

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public
          server-dir: /home/u2600287/data/www/corementa.online
